### ISSUE TITLE
License

### ISSUE THREAD

**Issue by calendee** [andrewmcgivery/ionic-ion-showWhen#2]
Andrew,

I've been loving all your posts and contributions.  Would you mind putting a license on this?  I'd be interested in incorporating it into a project.  Unfortunately, I can't do that if it doesn't have a non-restrictive license.  MIT maybe?

Thanks,
Justin

**Comment by andrewmcgivery** [comment]
Hey @calendee! Thanks!

Would you be open to submitting a pull request containing a license? :)
